import matter from 'matter-js'
import slingshot from './game/slingshot'
import bird from './game/bird'
import box from './game/box'
import ground from './game/ground'
import sketch from './game/sketch'